name: Auto PR on Change

on:
  push:
    branches:
      - main
      - gji11b-codex # 필요 브랜치명

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          title: "자동 PR: 변경점 감지"
          body: |
            새 변경점이 감지되어 자동으로 PR을 생성합니다.
            시안 파일, 사이드바 등 모든 변경사항 포함.
